## Stacked Area Plot

In [4]:
# setting
import string
import re
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

import matplotlib.pyplot as plt
import plotly
plotly.tools.set_credentials_file(username='crowwwww56', api_key='YNELI27nGE9bz8ZSFaxZ')
import plotly.plotly as py
import plotly.graph_objs as go

In [5]:
data = pd.read_csv("evolution_time_results.csv")
data = data[data['Project id'] == 129181598]
data = data.reset_index(drop=True)
data.head()

                                    Project  Project id Project date Project hour Abstraction  Parallelization  Logic  Synchronization  FlowControl  UserInteractivity  DataRepresent. TotalMastery AverageMastery         Level                 DefaultSpriteNames  TotalDefaultNames                                   DuplicateScripts  TotalDupScripts                                           DeadCode  Total blocks DeadCode                            AttributeInitialization  Total AttributeInitialization                                        Block Count Total blocks
0  129181598_2016-11-15-18-34-18.463567.sb2   129181598   2016-11-15        18:34           1              3.0    1.0              2.0          3.0                2.0             1.0        13/21         1.86/3    Developing  ['Sprite1', 'Sprite4', 'Sprite2']                3.0  ['when @greenFlag clicked', u'forever\n    swi...              1.0  {u'Tree': [['repeat until %s%s', 'play sound %...                    2.0  {u'Axe Man': 'position', u'Axe Man 2.0': 'posi...                            2.0  ['  1 hide variable %s', '  1 say %s for %s se...    182 total
1  129181598_2016-11-16-21-55-10.350285.sb2   129181598   2016-11-16        21:55           1              3.0    1.0              3.0          3.0                2.0             2.0        15/21         2.14/3   Proficiency  ['Sprite1', 'Sprite2', 'Sprite4']                3.0  ['when @greenFlag clicked', u'forever\n    swi...              1.0                      {u'Tree': [['set %s to %s']]}                    1.0  {u'Axe Man': 'position', u'Axe Man 2.0': 'posi...                            2.0  ['  1 stop all sounds', '  1 wait %s secs', ' ...    325 total
2  129181598_2016-11-16-20-53-07.627898.sb2   129181598   2016-11-16        20:53           1              3.0    1.0              3.0          3.0                2.0             2.0        15/21         2.14/3   Proficiency  ['Sprite1', 'Sprite4', 'Sprite2']                3.0  ['when @greenFlag clicked', u'forever\n    swi...              1.0  {u'Tree': [['set %s to %s'], ['go to x:%s y:%s...                    3.0  {u'Axe Man': 'position', u'Axe Man 2.0': 'posi...                            2.0  ['  1 stop all sounds', '  1 wait %s secs', ' ...    327 total
3  129181598_2016-11-14-16-56-16.662775.sb2   129181598   2016-11-14        16:56           1              1.0    1.0              2.0          3.0                2.0             1.0        11/21         1.57/3    Developing  ['Sprite2', 'Sprite1', 'Sprite4']                3.0  ['when @greenFlag clicked', u'forever\n    swi...              1.0                                                 []                    0.0  {u'Axe Man': 'position', u'Axe Man 2.0': 'posi...                            2.0  ['  1 play sound %s', '  1 say %s for %s secs'...    171 total
4  129181598_2016-11-14-16-43-11.631936.sb2   129181598   2016-11-14        16:43           1              1.0    1.0              2.0          3.0                2.0             1.0        11/21         1.57/3    Developing  ['Sprite2', 'Sprite1', 'Sprite4']                3.0  ['when @greenFlag clicked', u'forever\n    swi...              1.0                                                 []                    0.0  {u'Axe Man': 'position', u'Axe Man 2.0': 'posi...                            2.0  ['  1 play sound %s', '  1 say %s for %s secs'...    171 total

In [6]:
data = data[["Project date","Block Count"]]
data.shape

(132, 2)

In [7]:
data2 = data
data2["test"] = ""
data2

block_usage_cleaned = []
for i in data2.index:
    data2["Block Count"][i] = data2["Block Count"][i].strip("[]")
    data2["Block Count"][i] = data2["Block Count"][i].split(",")
    array = [item.replace(" '  ","").replace("'  ","").replace(" ' ","").replace("'","") for item in data2["Block Count"][i]]
    dic = {}
    for item in array:
        key = re.sub("\d ","",item)
        key = re.sub("\d","",key)
        key = re.sub("\d","",key)
        key = re.sub("\d","",key)
        key = re.sub("\d","",key)
        key = re.sub("\d","",key)
# not an elegent way but effective lol: adding multiple key = re.sub("\d","",key)
        value = item.split(" ")[0]
        dic[key] = value     
    block_usage_cleaned.append(dic)
    data2["test"][i] = dic
    i = i + 1
    
len(block_usage_cleaned)

132

In [9]:
data2.head()

  Project date                                        Block Count                                               test
0   2016-11-15  ['  1 hide variable %s',  '  1 say %s for %s s...  {'hide variable %s': '1', 'say %s for %s secs'...
1   2016-11-16  ['  1 stop all sounds',  '  1 wait %s secs',  ...  {'stop all sounds': '1', 'wait %s secs': '1', ...
2   2016-11-16  ['  1 stop all sounds',  '  1 wait %s secs',  ...  {'stop all sounds': '1', 'wait %s secs': '1', ...
3   2016-11-14  ['  1 play sound %s',  '  1 say %s for %s secs...  {'play sound %s': '1', 'say %s for %s secs': '...
4   2016-11-14  ['  1 play sound %s',  '  1 say %s for %s secs...  {'play sound %s': '1', 'say %s for %s secs': '...

In [10]:
df = pd.DataFrame(block_usage_cleaned)
df.head()

    %s %s = %s %s > %s %s or %s broadcast %s change %s by %s change x by %s change y by %s forever%s glide %s secs to x:%s y:%s go back %s layers go to x:%s y:%s hide hide variable %s if %s then%s if %s then%selse%s key %s pressed? play sound %s repeat until %s%s say %s say %s for %s secs set %s to %s set rotation style %s show show variable %s stop %s stop all sounds switch backdrop to %s switch costume to %s touching %s? touching color %s? wait %s secs when %s key pressed when @greenFlag clicked when I receive %s when backdrop switches to %s
0  NaN     NaN     NaN      NaN            7             NaN              6              6        15                          4                 1               7    7                1           27                NaN               4             2                 7    NaN                  1          NaN                     1    9              NaN     NaN             NaN                   NaN                   12           14                 15          NaN                 NaN                      29                 7                          NaN
1    5     NaN       2      NaN            8               1              6              6        15                          4                 1               5   44                3           30                NaN               4             2                 7      1                  3            3                     1   24                2     NaN               1                     4                   12           14                 17            1                 NaN                      50                25                           24
2    5     NaN       2      NaN            8               1              6              6        15                          4                 1               7   44                3           30                NaN               4             2                 7      1                  3            3                     1   24                2     NaN               1                     4                   12           14                 17            1                 NaN                      50                25                           24
3  NaN     NaN     NaN      NaN            6             NaN              6              6        15                          4                 1               7    6              NaN           27                NaN               4             1                 6    NaN                  1          NaN                     1    8              NaN     NaN             NaN                   NaN                   12           14                 15          NaN                 NaN                      25                 6                          NaN
4  NaN     NaN     NaN      NaN            6             NaN              6              6        15                          4                 1               7    6              NaN           27                NaN               4             1                 6    NaN                  1          NaN                     1    8              NaN     NaN             NaN                   NaN                   12           14                 15          NaN                 NaN                      25                 6                          NaN

In [11]:
df = df.fillna(0)
df.head()

  %s %s = %s %s > %s %s or %s broadcast %s change %s by %s change x by %s change y by %s forever%s glide %s secs to x:%s y:%s go back %s layers go to x:%s y:%s hide hide variable %s if %s then%s if %s then%selse%s key %s pressed? play sound %s repeat until %s%s say %s say %s for %s secs set %s to %s set rotation style %s show show variable %s stop %s stop all sounds switch backdrop to %s switch costume to %s touching %s? touching color %s? wait %s secs when %s key pressed when @greenFlag clicked when I receive %s when backdrop switches to %s
0  0       0       0        0            7               0              6              6        15                          4                 1               7    7                1           27                  0               4             2                 7      0                  1            0                     1    9                0       0               0                     0                   12           14                 15            0                   0                      29                 7                            0
1  5       0       2        0            8               1              6              6        15                          4                 1               5   44                3           30                  0               4             2                 7      1                  3            3                     1   24                2       0               1                     4                   12           14                 17            1                   0                      50                25                           24
2  5       0       2        0            8               1              6              6        15                          4                 1               7   44                3           30                  0               4             2                 7      1                  3            3                     1   24                2       0               1                     4                   12           14                 17            1                   0                      50                25                           24
3  0       0       0        0            6               0              6              6        15                          4                 1               7    6                0           27                  0               4             1                 6      0                  1            0                     1    8                0       0               0                     0                   12           14                 15            0                   0                      25                 6                            0
4  0       0       0        0            6               0              6              6        15                          4                 1               7    6                0           27                  0               4             1                 6      0                  1            0                     1    8                0       0               0                     0                   12           14                 15            0                   0                      25                 6                            0

In [126]:
block_cate = pd.read_csv("block_cate.csv")
block_cate.head()

  category                       block
0   motion               move %s steps
1   motion  turn @turnRight %s degrees
2   motion   turn @turnLeft %s degrees
3   motion       point in direction %s
4   motion            point towards %s

In [127]:
# turn it to dictionary like 'move %s steps': 'motion'

block_cate_dic = {}
for index in block_cate.index:
    key = block_cate["block"][index]
    value = block_cate["category"][index]
    block_cate_dic[key] = value

In [86]:
df = df.rename(columns = block_cate_dic)

In [87]:
df.shape

(132, 36)

In [128]:
df.head()

  %s operators operators operators events data motion motion control motion looks motion looks data control control sensing sound control looks looks set %s to %s motion looks data control sound looks looks sensing sensing control events events events events
0  0         0         0         0      7    0      6      6      15      4     1      7     7    1      27       0       4     2       7     0     1            0      1     9    0       0     0     0    12      14      15       0      0     29      7      0
1  5         0         2         0      8    1      6      6      15      4     1      5    44    3      30       0       4     2       7     1     3            3      1    24    2       0     1     4    12      14      17       1      0     50     25     24
2  5         0         2         0      8    1      6      6      15      4     1      7    44    3      30       0       4     2       7     1     3            3      1    24    2       0     1     4    12      14      17       1      0     50     25     24
3  0         0         0         0      6    0      6      6      15      4     1      7     6    0      27       0       4     1       6     0     1            0      1     8    0       0     0     0    12      14      15       0      0     25      6      0
4  0         0         0         0      6    0      6      6      15      4     1      7     6    0      27       0       4     1       6     0     1            0      1     8    0       0     0     0    12      14      15       0      0     25      6      0

In [89]:
df_test = df

In [90]:
df_test = pd.DataFrame(df,dtype=np.float)

In [92]:
df_test["motion"] = df_test["motion"].sum(axis=1)
df_test = df_test.T.drop_duplicates()
df_test = df_test.T

In [93]:
df_test["looks"] = df_test["looks"].sum(axis=1)
df_test = df_test.T.drop_duplicates()
df_test = df_test.T

In [94]:
df_test["sound"] = df_test["sound"].sum(axis=1)
df_test = df_test.T.drop_duplicates()
df_test = df_test.T

In [95]:
# not in this project, if run, keyerror
# should make pen all zero, fix this!!!

# df_test["pen"] = df_test["pen"].sum(axis=1)
# df_test = df_test.T.drop_duplicates()
# df_test = df_test.T
df_test["pen"] = 0

In [96]:
df_test["events"] = df_test["events"].sum(axis=1)
df_test = df_test.T.drop_duplicates()
df_test = df_test.T

In [97]:
#df_test["more"] = df_test["more"].sum(axis=1)
#df_test = df_test.T.drop_duplicates()
#df_test = df_test.T
df_test["more"] = 0.0

In [98]:
df_test["operators"] = df_test["operators"].sum(axis=1)
df_test = df_test.T.drop_duplicates()
df_test = df_test.T

In [99]:
df_test["data"] = df_test["data"].sum(axis=1)
df_test = df_test.T.drop_duplicates()
df_test = df_test.T

In [100]:
df_test["sensing"] = df_test["sensing"].sum(axis=1)
df_test = df_test.T.drop_duplicates()
df_test = df_test.T

In [101]:
df_test["control"] = df_test["control"].sum(axis=1)
df_test = df_test.T.drop_duplicates()
df_test = df_test.T

In [103]:
df_test["more"] = 0.0

In [105]:
df_plot = pd.concat([data[["Project date"]],df_test[["motion","looks","sound","events","pen","more","operators","data","sensing","control"]]],axis = 1)

In [129]:
# filter date "2016-12-09"
df_plot = df_plot[df_plot['Project date']!="2016-12-09"].reset_index(drop=True)

In [130]:
df_plot.head()

  Project date  motion  looks  sound  events  pen  more  operators  data  sensing  control
0   2016-11-15    24.0   30.0    2.0    43.0  0.0   0.0        0.0   1.0     33.0     49.0
1   2016-11-16    22.0   89.0    3.0   107.0  0.0   0.0        2.0   6.0     35.0     53.0
2   2016-11-16    24.0   89.0    3.0   107.0  0.0   0.0        2.0   6.0     35.0     53.0
3   2016-11-14    24.0   28.0    1.0    37.0  0.0   0.0        0.0   0.0     33.0     48.0
4   2016-11-14    24.0   28.0    1.0    37.0  0.0   0.0        0.0   0.0     33.0     48.0

In [125]:
# actual date
trace_motion = dict(
    x=df_plot["Project date"],
    y=df_plot["motion"],
    hoverinfo='x+y',
    mode='lines',
    name = "Motion block count",
    line=dict(width=1,
              color=1),
    stackgroup='one'
)
trace_looks = dict(
    x=df_plot["Project date"],
    y=df_plot["looks"],
    hoverinfo='x+y',
    mode='lines',
    name = "Looks block count",
    line=dict(width=1,
              color=2),
    stackgroup='one'
)
trace_sound = dict(
    x=df_plot["Project date"],
    y=df_plot["sound"],
    hoverinfo='x+y',
    mode='lines',
    name = "Sound block count",
    line=dict(width=1,
              color=3),
    stackgroup='one'
)
trace_events = dict(
    x=df_plot["Project date"],
    y=df_plot["events"],
    hoverinfo='x+y',
    mode='lines',
    name = "Events block count",
    line=dict(width=1,
              color=4),
    stackgroup='one'
)
trace_pen = dict(
    x=df_plot["Project date"],
    y=df_plot["pen"],
    hoverinfo='x+y',
    mode='lines',
    name = "Pen block count",
    line=dict(width=1,
              color=5),
    stackgroup='one'
)
trace_more = dict(
    x=df_plot["Project date"],
    y=df_plot["more"],
    hoverinfo='x+y',
    mode='lines',
    name = "More block count",
    line=dict(width=1,
              color=6),
    stackgroup='one'
)
trace_operators = dict(
    x=df_plot["Project date"],
    y=df_plot["operators"],
    hoverinfo='x+y',
    mode='lines',
    name = "Operators block count",
    line=dict(width=1,
              color=7),
    stackgroup='one'
)
trace_data = dict(
    x=df_plot["Project date"],
    y=df_plot["data"],
    hoverinfo='x+y',
    mode='lines',
    name = "Data block count",
    line=dict(width=1,
              color=8),
    stackgroup='one'
)
trace_sensing = dict(
    x=df_plot["Project date"],
    y=df_plot["sensing"],
    hoverinfo='x+y',
    mode='lines',
    name = "Sensing block count",
    line=dict(width=1,
              color=9),
    stackgroup='one'
)
trace_control = dict(
    x=df_plot["Project date"],
    y=df_plot["control"],
    hoverinfo='x+y',
    mode='lines',
    name = "Control block count",
    line=dict(width=1,
              color=10),
    stackgroup='one'
)

data_stacked = [trace_events, trace_looks, trace_control, trace_sensing, trace_motion, trace_data, trace_sound,trace_operators, trace_pen, trace_more]

layout = dict(
    title='Block usage of project 129181598'
)

fig_100 = dict(data=data_stacked,layout=layout)
py.iplot(fig_100, filename='Block usage of project 129181598', validate=False)